eventary/views/anonymous.py, eventary/views/editorial.py, eventary/views/management.py, eventary/views/mixins.py
=> Access restrictions #2

eventary/templates/eventary/navigation/editorial.html, eventary/templates/eventary/navigation/management.html, eventary/templatetags/eventary_tags.py
- also reorganizes the template tags alphabetically
- refactors the logic obtaining the users eventary auth group
- fixes if if else error -> if elif else
=> Adds the eventary_auth_group template tag

eventary/urls.py, eventary/views/anonymous.py
also includes HttpResponseForbidden if accessing secret url more than
the limit of views set
=> consolidates url arguments

eventary/templates/eventary/management/landing.html, eventary/views/management.py
- event_list is a django query object
- event_page is a paginator page
=> we now pass a event_page and an event_list

eventary/tests/test_pagination_and_filtering.py, eventary/views/management.py
also removes an unneeded import
=> tests filters

eventary/tests/test_pagination_and_filtering.py
=> Adds tests for filtering multiday events

eventary/tests/mixins.py, eventary/tests/test_anonymous_access.py, eventary/tests/test_business_logic.py, eventary/tests/test_editorial_access.py, eventary/tests/test_management_access.py
- adds access test mixin
- moves definition of "special cases" to setUp method
=> Refactors and improves access tests

eventary/views/mixins.py
even when the filter is not set!
=> sorts events by recurrence

eventary/tests/test_event_ordering.py, eventary/views/anonymous.py, eventary/views/editorial.py
=> Correctly filters events for calendars

eventary/static/js/recurrences_wizard.js, eventary/templates/eventary/anonymous/create_event_wizard.html, eventary/urls.py, eventary/views/anonymous.py, setup.py
Adds a form wizard to propose events with the following steps:
- 0: host information
- 1: event & grouping information
- 2: date, time & recurrence information
the grouping form only appears if groupings where assigned to the
calendar. recurrence form only appears if the event was declared to be a
recurring event.
=> Form wizard for event creation

eventary/forms.py, eventary/static/css/groupingform.css, eventary/static/js/groupingform.js, eventary/templates/eventary/anonymous/create_event_wizard.html, eventary/templates/eventary/wizard_pagination.html, eventary/templatetags/eventary_tags.py, eventary/urls.py, eventary/views/anonymous.py, eventary/views/editorial.py
- also improve the way media is included
- also add a wizard pagination
- also load initial data
closes #85 #67
=> Use an event wizard to update the events

eventary/forms.py, eventary/static/css/filterform.css, eventary/static/js/filterform.js, eventary/templates/eventary/anonymous/calendar_details.html, eventary/templates/eventary/anonymous/landing.html, eventary/templates/eventary/editorial/landing.html, eventary/templates/eventary/editorial/list_proposals.html, eventary/templates/eventary/management/landing.html
- also adds media for filter form
=> Improves filter form spacing

eventary/views/mixins.py
=> Default filter from now to in a week

eventary/templates/eventary/anonymous/calendar_details.html, eventary/templates/eventary/anonymous/landing.html, eventary/templates/eventary/editorial/landing.html, eventary/templates/eventary/editorial/list_calendars.html, eventary/templates/eventary/editorial/list_proposals.html, eventary/templates/eventary/lists/calendars.html, eventary/templates/eventary/lists/events.html, eventary/templates/eventary/management/landing.html, eventary/templates/eventary/management/list_calendars.html
=> Refactors lists

eventary/views/mixins.py
=> Fixes default filter for events and proposals

eventary/templates/eventary/anonymous/published_event.ics, eventary/templatetags/eventary_tags.py
- including recurrence
- organizer
- title
- description
=> Improves ICS export for events

eventary/templates/eventary/anonymous/create_event_wizard.html, eventary/templates/eventary/wizard_buttons.html, eventary/templates/eventary/wizard_status.html, eventary/templatetags/eventary_tags.py, eventary/views/anonymous.py, eventary/views/editorial.py
+ stores the state of the forms when jumping back
+ displays buttons for all the steps of the pagination
+ displays meaningful button titles
+- renames wizard_pagination to wizard_buttons
- removes EventCreateView (since replaced with EventCreateWizardView)
- removes EventEditView (since replaced with EventEditWizardView)
closes #114
=> improves wizard pagination

eventary/forms.py, setup.py
don't forget to make a django-datetimepicker package!
=> uses datetimepicker without bootstrap3

README.rst, eventary/forms.py, eventary/views/mixins.py
Implements simple fulltext search using postgre's integrated fulltext search
=> full text search

eventary/views/mixins.py
When using the page navigation, get parameters are set.
In that case the FilterForm got a non-empty request.GET, such that
prefilled fields' initial values did not appear.
The initial values need to be added to the data passed to the FilterForm
if a non-empty request.GET is received.
...and while we're at it, some of the FilterFormMixin's code was
refactored.
See issue 112 on veranstaltungen_winterthur
=> Fix prefilled values after page navigation

eventary/views/mixins.py
Instead of using _all_ events, we need to use only the ones from the
visited Calendar.
=> Fix support for multiple clients

eventary/forms.py
Source code before sorting:
Source code after sorting:
=> Sort filters by name

eventary/models/base.py, eventary/templates/eventary/lists/events.html
As requested by the client in https://extranet.4teamwork.ch/support/stadt-winterthur/tracker-web/109#re425faf8
=> Order the tags by their grouping, then by their title.

eventary/models/base.py
This has already been installed at the client's site and the client has approved it.
=> Improve the upload path (again).
